<a href="https://colab.research.google.com/github/sourcecode369/TensorFlow-2.0/blob/master/tensorflow_2.0_docs/TensorFlow%20Core/Tutorials/Load%20and%20Preprocess%20Data/CSV%20Data/TensorFlow_2_0_Load_and_preprocess_data_Load_CSV_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install --upgrade tensorflow-gpu

     |████████████████████████████████| 380.8MB 43kB/s 
     |████████████████████████████████| 3.8MB 34.5MB/s 
     |████████████████████████████████| 450kB 52.8MB/s 
     |████████████████████████████████| 81kB 10.9MB/s 
ERROR: tensorflow 1.15.0 has requirement tensorboard<1.16.0,>=1.15.0, but you'll have tensorboard 2.0.1 which is incompatible.
ERROR: tensorflow 1.15.0 has requirement tensorflow-estimator==1.15.1, but you'll have tensorflow-estimator 2.0.1 which is incompatible.
ERROR: tensorboard 2.0.1 has requirement grpcio>=1.24.3, but you'll have grpcio 1.15.0 which is incompatible.
ERROR: google-colab 1.0.0 has requirement google-auth~=1.4.0, but you'll have google-auth 1.6.3 which is incompatible.
  Found existing installation: google-auth 1.4.2
    Uninstalling google-auth-1.4.2:
      Successfully uninstalled google-auth-1.4.2
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0
  Found exist

In [0]:
from __future__ import absolute_import, print_function, division, unicode_literals
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
TRAIN_DATA_URL = "https://storage.googleapis.com/tf-datasets/titanic/train.csv"
TEST_DATA_URL = "https://storage.googleapis.com/tf-datasets/titanic/eval.csv"

train_file_path = tf.keras.utils.get_file("train.csv",TRAIN_DATA_URL)
test_file_path = tf.keras.utils.get_file('test.csv',TEST_DATA_URL)

np.set_printoptions(precision=3)

16384/13049 [=====================================] - 0s 0us/step


In [4]:
!head {train_file_path}

survived,sex,age,n_siblings_spouses,parch,fare,class,deck,embark_town,alone
0,male,22.0,1,0,7.25,Third,unknown,Southampton,n
1,female,38.0,1,0,71.2833,First,C,Cherbourg,n
1,female,26.0,0,0,7.925,Third,unknown,Southampton,y
1,female,35.0,1,0,53.1,First,C,Southampton,n
0,male,28.0,0,0,8.4583,Third,unknown,Queenstown,y
0,male,2.0,3,1,21.075,Third,unknown,Southampton,n
1,female,27.0,0,2,11.1333,Third,unknown,Southampton,n
1,female,14.0,1,0,30.0708,Second,unknown,Cherbourg,n
1,female,4.0,1,1,16.7,Third,G,Southampton,n


In [0]:
LABEL_COLUMN = 'survived'
LABELS = [0, 1]

In [9]:
def get_dataset(filepath, **kwargs):
  dataset = tf.data.experimental.make_csv_dataset(
      filepath,
      batch_size=5,
      label_name=LABEL_COLUMN,
      na_value="?",
      num_epochs=1,
      ignore_errors=True,
      **kwargs
  )
  return dataset

raw_train_data = get_dataset(train_file_path)
raw_test_data = get_dataset(test_file_path)

Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.experimental.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_determinstic`.


In [10]:
raw_train_data.element_spec

(OrderedDict([('sex', TensorSpec(shape=(None,), dtype=tf.string, name=None)),
              ('age', TensorSpec(shape=(None,), dtype=tf.float32, name=None)),
              ('n_siblings_spouses',
               TensorSpec(shape=(None,), dtype=tf.int32, name=None)),
              ('parch', TensorSpec(shape=(None,), dtype=tf.int32, name=None)),
              ('fare', TensorSpec(shape=(None,), dtype=tf.float32, name=None)),
              ('class', TensorSpec(shape=(None,), dtype=tf.string, name=None)),
              ('deck', TensorSpec(shape=(None,), dtype=tf.string, name=None)),
              ('embark_town',
               TensorSpec(shape=(None,), dtype=tf.string, name=None)),
              ('alone',
               TensorSpec(shape=(None,), dtype=tf.string, name=None))]),
 TensorSpec(shape=(None,), dtype=tf.int32, name=None))

In [11]:
raw_test_data.element_spec

(OrderedDict([('sex', TensorSpec(shape=(None,), dtype=tf.string, name=None)),
              ('age', TensorSpec(shape=(None,), dtype=tf.float32, name=None)),
              ('n_siblings_spouses',
               TensorSpec(shape=(None,), dtype=tf.int32, name=None)),
              ('parch', TensorSpec(shape=(None,), dtype=tf.int32, name=None)),
              ('fare', TensorSpec(shape=(None,), dtype=tf.float32, name=None)),
              ('class', TensorSpec(shape=(None,), dtype=tf.string, name=None)),
              ('deck', TensorSpec(shape=(None,), dtype=tf.string, name=None)),
              ('embark_town',
               TensorSpec(shape=(None,), dtype=tf.string, name=None)),
              ('alone',
               TensorSpec(shape=(None,), dtype=tf.string, name=None))]),
 TensorSpec(shape=(None,), dtype=tf.int32, name=None))

In [13]:
def show_batch(dataset):
  for batch, label in dataset.take(1):
    for key, value in batch.items():
      print("{:20s}: {}".format(key, value.numpy()))

show_batch(raw_train_data)

sex                 : [b'female' b'male' b'male' b'female' b'male']
age                 : [ 4. 28. 31. 28. 28.]
n_siblings_spouses  : [0 0 1 8 0]
parch               : [1 0 1 2 0]
fare                : [13.417  8.05  37.004 69.55   7.854]
class               : [b'Third' b'Third' b'Second' b'Third' b'Third']
deck                : [b'unknown' b'unknown' b'unknown' b'unknown' b'unknown']
embark_town         : [b'Cherbourg' b'Southampton' b'Cherbourg' b'Southampton' b'Southampton']
alone               : [b'n' b'y' b'n' b'n' b'y']


In [14]:
CSV_COLUMNS = ['survived', 'sex', 'age', 'n_siblings_spouses', 'parch', 'fare', 'class', 'deck', 'embark_town', 'alone']
temp_dataset = get_dataset(train_file_path, column_names=CSV_COLUMNS)
show_batch(temp_dataset)

sex                 : [b'male' b'male' b'female' b'male' b'male']
age                 : [36. 33. 19. 32. 23.]
n_siblings_spouses  : [0 0 0 0 0]
parch               : [0 0 0 0 0]
fare                : [40.125  9.5   26.     8.05   7.896]
class               : [b'First' b'Third' b'Second' b'Third' b'Third']
deck                : [b'A' b'unknown' b'unknown' b'E' b'unknown']
embark_town         : [b'Cherbourg' b'Southampton' b'Southampton' b'Southampton' b'Southampton']
alone               : [b'y' b'y' b'y' b'y' b'y']


In [15]:
SELECT_COLUMNS = ['survived', 'age', 'n_siblings_spouses', 'class', 'deck', 'alone']
temp_dataset = get_dataset(train_file_path, select_columns=SELECT_COLUMNS)
show_batch(temp_dataset)

age                 : [32. 28. 28. 50. 22.]
n_siblings_spouses  : [0 0 0 0 0]
class               : [b'Third' b'First' b'Third' b'Second' b'First']
deck                : [b'E' b'C' b'unknown' b'unknown' b'B']
alone               : [b'y' b'y' b'y' b'y' b'n']


### Data Preprocessing

#### Numeric Columns

In [16]:
SELECT_COLUMNS = ['survived', 'age', 'n_siblings_spouses', 'parch', 'fare']
DEFAULTS = [0, 0.0, 0.0, 0.0, 0.0]
temp_dataset = get_dataset(train_file_path, 
                           select_columns=SELECT_COLUMNS,
                           column_defaults = DEFAULTS)
show_batch(temp_dataset)

age                 : [19. 28. 28. 28. 16.]
n_siblings_spouses  : [0. 0. 0. 0. 4.]
parch               : [0. 0. 0. 0. 1.]
fare                : [ 8.05  14.5    7.75   7.896 39.688]


In [0]:
example_batch, labels_batch = next(iter(temp_dataset))

In [0]:
def pack(features, label):
  return tf.stack(list(features.values()), axis=1), label

In [21]:
packed_dataset = temp_dataset.map(pack, num_parallel_calls=tf.data.experimental.AUTOTUNE)

for features, label in packed_dataset.take(1):
  print(features.numpy())
  print()
  print(label.numpy())

[[ 28.      0.      0.      7.05 ]
 [ 28.      1.      2.     23.45 ]
 [ 22.      0.      0.    151.55 ]
 [ 17.      0.      0.      8.663]
 [ 48.      1.      0.     39.6  ]]

[0 0 1 0 1]


In [22]:
show_batch(raw_train_data)

sex                 : [b'male' b'female' b'male' b'male' b'female']
age                 : [40. 14. 28. 31. 17.]
n_siblings_spouses  : [0 1 3 0 1]
parch               : [0 0 1 0 0]
fare                : [  7.896  30.071  25.467  13.    108.9  ]
class               : [b'Third' b'Second' b'Third' b'Second' b'First']
deck                : [b'unknown' b'unknown' b'unknown' b'unknown' b'C']
embark_town         : [b'Southampton' b'Cherbourg' b'Southampton' b'Southampton' b'Cherbourg']
alone               : [b'y' b'n' b'n' b'y' b'n']


In [0]:
example_batch, labels_batch = next(iter(temp_dataset))

In [0]:
class PackNumericFeature(object):
  def __init__(self, names):
    self.names = names

  def __call__(self, features, labels):
    numeric_features = [features.pop(name) for name in self.names]
    numeric_features = [tf.cast(feat, tf.float32) for feat in numeric_features]
    numeric_features = tf.stack(numeric_features, axis=-1)
    features['numeric'] = numeric_features
    return features, labels

In [0]:
NUMERIC_FEATURES = ['age','n_siblings_spouses','parch', 'fare']
packed_train_data = raw_train_data.map(PackNumericFeature(NUMERIC_FEATURES), num_parallel_calls=tf.data.experimental.AUTOTUNE)
packed_test_data = raw_test_data.map(PackNumericFeature(NUMERIC_FEATURES), num_parallel_calls=tf.data.experimental.AUTOTUNE)

In [27]:
show_batch(packed_train_data)

sex                 : [b'male' b'female' b'female' b'male' b'male']
class               : [b'Third' b'Third' b'Second' b'First' b'Second']
deck                : [b'F' b'unknown' b'unknown' b'unknown' b'unknown']
embark_town         : [b'Southampton' b'Southampton' b'Southampton' b'Cherbourg' b'Southampton']
alone               : [b'y' b'y' b'n' b'y' b'n']
numeric             : [[19.     0.     0.     7.65 ]
 [ 5.     0.     0.    12.475]
 [26.     1.     1.    26.   ]
 [28.     0.     0.    30.696]
 [29.     1.     0.    21.   ]]


In [0]:
example_batch, label_batch = next(iter(packed_train_data))

In [29]:
desc = pd.read_csv(train_file_path)[NUMERIC_FEATURES].describe()
desc

age  n_siblings_spouses       parch        fare
count  627.000000          627.000000  627.000000  627.000000
mean    29.631308            0.545455    0.379585   34.385399
std     12.511818            1.151090    0.792999   54.597730
min      0.750000            0.000000    0.000000    0.000000
25%     23.000000            0.000000    0.000000    7.895800
50%     28.000000            0.000000    0.000000   15.045800
75%     35.000000            1.000000    0.000000   31.387500
max     80.000000            8.000000    5.000000  512.329200

In [0]:
MEAN = desc.T["mean"].values
STD = desc.T["std"].values

In [0]:
def normalize_numeric_data(data, mean, std):
  return (data-mean)/std

In [32]:
import functools
normalizer = functools.partial(normalize_numeric_data, mean=MEAN, std=STD)
numeric_column = tf.feature_column.numeric_column('numeric', normalizer_fn=normalizer, shape=[len(NUMERIC_FEATURES)])
numeric_column

NumericColumn(key='numeric', shape=(4,), default_value=None, dtype=tf.float32, normalizer_fn=functools.partial(<function normalize_numeric_data at 0x7efce88597b8>, mean=array([29.631,  0.545,  0.38 , 34.385]), std=array([12.512,  1.151,  0.793, 54.598])))

In [33]:
example_batch['numeric']

<tf.Tensor: id=852, shape=(5, 4), dtype=float32, numpy=
array([[39.   ,  0.   ,  0.   , 26.   ],
       [ 4.   ,  0.   ,  2.   , 22.025],
       [15.   ,  1.   ,  0.   , 14.454],
       [47.   ,  1.   ,  1.   , 52.554],
       [21.   ,  0.   ,  0.   ,  7.775]], dtype=float32)>

In [35]:
numeric_layer = tf.keras.layers.DenseFeatures(numeric_column)
numeric_layer(example_batch).numpy()

array([[ 0.749, -0.474, -0.479, -0.154],
       [-2.049, -0.474,  2.043, -0.226],
       [-1.169,  0.395, -0.479, -0.365],
       [ 1.388,  0.395,  0.782,  0.333],
       [-0.69 , -0.474, -0.479, -0.487]], dtype=float32)

#### Categorical Columns

In [0]:
CATEGORIES = {
    'sex': ['male', 'female'],
    'class' : ['First', 'Second', 'Third'],
    'deck' : ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
    'embark_town' : ['Cherbourg', 'Southhampton', 'Queenstown'],
    'alone' : ['y', 'n']
}

In [0]:
categorical_columns = []
for feature, vocab in CATEGORIES.items():
  cat_col = tf.feature_column.categorical_column_with_vocabulary_list(
      key=feature, vocabulary_list=vocab
  )
  cat_col = tf.feature_column.indicator_column(cat_col)
  categorical_columns.append(cat_col)

In [49]:
categorical_columns

[IndicatorColumn(categorical_column=VocabularyListCategoricalColumn(key='sex', vocabulary_list=('male', 'female'), dtype=tf.string, default_value=-1, num_oov_buckets=0)),
 IndicatorColumn(categorical_column=VocabularyListCategoricalColumn(key='class', vocabulary_list=('First', 'Second', 'Third'), dtype=tf.string, default_value=-1, num_oov_buckets=0)),
 IndicatorColumn(categorical_column=VocabularyListCategoricalColumn(key='deck', vocabulary_list=('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'), dtype=tf.string, default_value=-1, num_oov_buckets=0)),
 IndicatorColumn(categorical_column=VocabularyListCategoricalColumn(key='embark_town', vocabulary_list=('Cherbourg', 'Southhampton', 'Queenstown'), dtype=tf.string, default_value=-1, num_oov_buckets=0)),
 IndicatorColumn(categorical_column=VocabularyListCategoricalColumn(key='alone', vocabulary_list=('y', 'n'), dtype=tf.string, default_value=-1, num_oov_buckets=0))]

In [0]:
categorical_layer = tf.keras.layers.DenseFeatures(categorical_columns)

In [54]:
print(categorical_layer(example_batch).numpy()[0])

[1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]


### Combined Preprocessing

In [58]:
preprocessing_layer = tf.keras.layers.DenseFeatures([numeric_column]+categorical_columns)
print(preprocessing_layer(example_batch).numpy()[0])

[ 1.     0.     0.     1.     0.     0.     0.     0.     0.     0.
  0.     0.     0.     0.     0.     0.     0.     0.     0.749 -0.474
 -0.479 -0.154  1.     0.   ]


In [0]:
strategy = tf.distribute.MirroredStrategy(cross_device_ops=tf.distribute.NcclAllReduce())

In [0]:
with strategy.scope():
  model = tf.keras.Sequential([
                              preprocessing_layer,
                              tf.keras.layers.Dense(256, activation=tf.nn.relu),
                              tf.keras.layers.Dense(128, activation=tf.nn.relu),
                              tf.keras.layers.Dense(1, activation=tf.nn.sigmoid)
  ])

  model.compile(
      loss='binary_crossentropy',
      optimizer='adam',
      metrics=['accuracy']
  )

In [0]:
train_data = packed_train_data.shuffle(500)
test_data = packed_test_data

In [68]:
with strategy.scope():
  model.fit(train_data, 
            epochs=50, 
            validation_data=test_data, 
            verbose=1,
            callbacks=[tf.keras.callbacks.ReduceLROnPlateau(monitor='val_loss',patience=2,verbose=1),
                       tf.keras.callbacks.EarlyStopping(monitor='val_loss',patience=5,verbose=1)])

Epoch 1/50
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
INFO:tensorflow:Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
126/126 [==============================] - 4s 29ms/step - loss: 0.3367 - accuracy: 0.8628 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 2/50
126/126 [==============================] - 1s 9ms/step - loss: 0.3384 - accuracy: 0.8628 - val_loss: 0.4202 - val_accuracy: 0.8409
Epoch 3/50
126/126 [==============================] - 1s 9ms/step - loss: 0.3476 - accuracy: 0.8628 - val_loss: 0.4162 - val_accuracy: 0.8409
Epoch 4/50
126/126 [==============================] - 1s 9ms/step - loss: 0.3411 - accuracy: 0.8628 - val_loss: 0.4166 - val_accuracy: 0.8409
Epoch 5/50
49/53 [==========================>...] - ETA: 0s - loss: 0.3364 - accuracy: 0.8694
Epoch 00005: ReduceLROnPlateau reducing learning 

In [70]:
test_loss, test_accuracy = model.evaluate(test_data)

print('\n\nTest Loss {:.2f}, Test Accuracy {:.2f}'.format(test_loss, test_accuracy))

53/53 [==============================] - 2s 35ms/step - loss: 0.4178 - accuracy: 0.8409


Test Loss 0.42, Test Accuracy 0.84


In [71]:
predictions = model.predict(test_data)

for prediction, survived in zip(predictions[:10], list(test_data)[0][1][:10]):
  print("Predicted survival: {:.2%}".format(prediction[0]),
        " | Actual outcome: ",
        ("SURVIVED" if bool(survived) else "DIED"))

Predicted survival: 33.84%  | Actual outcome:  DIED
Predicted survival: 30.88%  | Actual outcome:  DIED
Predicted survival: 19.34%  | Actual outcome:  SURVIVED
Predicted survival: 82.43%  | Actual outcome:  DIED
Predicted survival: 99.06%  | Actual outcome:  DIED
